Build dashboard
wikimedia/toolhunt-ui pull request #14
Opened 2023-01-10 08:44 UTC by nbarnabee

I'm throwing up my preliminary work here so that anyone who wants to can take a look and offer comments.

2023-01-10 15:30 UTC, nbarnabee commented
The tables need more styling and I haven't attempted to throw in a pretty chart like I did with my contribution work, but I think I have the general shape of it now and also have a good idea of the shape of the data I'd like to fetch.  Second opinions welcome!

2023-01-11 12:41 UTC, Damilare1 requested changes
Looks good to me, just a couple of suggestions inline

2023-01-11 12:41 UTC, Damilare1 commented on src/components/ContributionTable.vue
> +    global: Boolean,
Can you share what the global prop flag represents?

2023-01-11 12:41 UTC, Damilare1 commented on src/components/ContributionTable.vue
> +  methods: {
I believe these methods may be best used in the `compute` property instead of `methods`. This is because of the `compute` caching property, this property ensures that the computation within the method is not repeated unless the parameters are changed (i.e memoization). These methods don't seem too complicated so we might not really see the difference, however it'd be more obvious if we had a complicated array traversal or async function call.

I'd recommend the use of compute for this kind of computations.


For more info, see this [StackOverflow](https://stackoverflow.com/questions/44350862/methods-vs-computed-in-vue) thread.

2023-01-11 13:29 UTC, nbarnabee commented on src/components/ContributionTable.vue
> +                <a :href=generateProfileURL(contribution.user) target="_blank">{{ contribution.user }}</a></td>
Here's where I make use of the global prop flag.  I was looking for a way to distinguish between a table component that would display the current user's activity and one that would display the latest global activity; in the case of the global table, I wanted to include the username of whomever made the contribution.

I thought about doing something like  `<td v-if="contribution.user != currentUser">` but realized that that would produce undesired results if the current user was responsible for an item on the "latest activity" table.

2023-01-11 13:31 UTC, nbarnabee commented on src/components/ContributionTable.vue
> +  methods: {
That makes sense; thanks for the input!  I'll refactor this.

2023-01-11 14:37 UTC, nbarnabee commented on src/components/ContributionTable.vue
> +  methods: {
Looking at it again, I'm not sure that using `compute` will work, as I'm passing parameters into the functions.  See this other [Stack Overflow](https://stackoverflow.com/questions/40522634/can-i-pass-parameters-in-computed-properties-in-vue-js) thread.  

There seems to be a roundabout method of doing it, or I could potentially write a setter function to go with the getter, but then I'd be calling both getter and setter for each `<td>` that was being rendered.  

I'm basically using these methods to mutate the incoming data.  Some of it, like the generation of URLs, could be done server-side.  Generation of a locale-specific date string I'd want to do on the client-side... though I suppose I could theoretically get information about the client's location from the request headers... but that seems like an overly complicated solution.

Sorry if I start to ramble here, I'm just thinking about the underlying architecture.  Every time the Dashboard component is mounted it will make a fetch request to our API and get back (among other things) an array of objects containing information about the most recent edits, which it passes to this component.   Then this component converts every dateString, userName and toolName in every object into a localeDateString and two URLs and uses those to render the tables.

If I wanted to cache anything, it might be the original array of objects?  But if the user leaves the dashboard and, say, goes to the homepage and makes a change, then on return to the leaderboard I'd need to refresh the "my contributions" table anyway.

2023-01-11 15:30 UTC, Damilare1 commented on src/components/ContributionTable.vue
> +  methods: {
Looks like the methods are essentially all getters returning modified state values.
Hmm, about the parameters: I think with compute, you can access the state variable directly in the method without having to pass it in as a parameter.

for example the userProfileURL can be simplified to this (untested). Let me know if this works for you.

```
<a :href={{ userProfileURL }} target="_blank">{{ contribution.user }}</a>
computed: {
  userProfileURL: function () {
    let userName = contribution?.user.split(" ").join("_")
    return `https://en.wikipedia.org/wiki/User:${userName}`
  }
}
```

2023-01-11 15:44 UTC, Damilare1 commented on src/components/ContributionTable.vue
> +  methods: {
Sorry, I see what you mean. You're looping through the values of the content. We could make the children of the `tr ` a component and do this compute within the component using the props.

2023-01-11 21:01 UTC, nbarnabee commented on src/components/ContributionTable.vue
> +  methods: {
Done!  (See commits [26ffaf0](https://github.com/wikimedia/toolhunt-ui/pull/14/commits/26ffaf05a63510e22dacd2f4832f6987add94b75) and [6077460](https://github.com/wikimedia/toolhunt-ui/pull/14/commits/6077460e2ce53a98e16038908a46c886df3371d9)

2023-01-11 21:14 UTC, Damilare1 approved these changes

2023-01-12 15:44 UTC, HWaruguru commented
Looks good maybe we can review it later if time allows to make the numbers pop out a little bit more

2023-01-12 15:44 UTC, HWaruguru approved these changes

2023-01-12 15:45 UTC, merged