HomeView: Add home page
wikimedia/toolhunt-ui pull request #16
Opened 2023-01-12 21:53 UTC by HWaruguru

This is a work-in-progress for the home page component

Task: [T326870](https://phabricator.wikimedia.org/T326870)

2023-01-15 21:13 UTC, nbarnabee approved these changes
Looks good.

2023-01-16 05:12 UTC, nbarnabee commented
In hindsight, I probably shouldn't review things right before bed.  We may not want to have a search bar in there at the moment, since a search option wasn't going to be part of the MVP.

2023-01-16 07:52 UTC, HWaruguru commented
That's right let me work on it

2023-01-18 08:06 UTC, Damilare1 requested changes
Looks good, just a small suggestion and we'd be good to go.

2023-01-18 08:06 UTC, Damilare1 commented on plugins/vuetify.js
> +import '@mdi/font/css/materialdesignicons.css';
Looks like we didn't get to use any icon from this import. I'd suggest we take it off for now.

2023-01-18 09:59 UTC, Damilare1 approved these changes

2023-01-18 09:59 UTC, merged