Propagate currentUser value throughout frontend
wikimedia/toolhunt-ui pull request #39
Opened 2023-03-06 00:22 UTC by nbarnabee

I know that this is stepping outside of my territory, but I was trying to solve a problem we were having on the backend (the async tasks that handle PUT requests appear to be acting outside of the session, so we couldn't keep "hold" of the username) and ended up doing more than that.

I shifted the call for `getLoggedInUser()` to App.vue and passed the prop value to the Navbar, down through the views, added it to the payload that's delivered to the backend on a PUT request.

2023-03-06 10:30 UTC, nbarnabee commented
This PR requires https://github.com/wikimedia/toolhunt/pull/47 on the backend.

2023-03-07 08:02 UTC, Damilare1 requested changes
Hi @nbarnabee, there are no teritories on this project 😊. You're welcome to add improvements anytime. 

This PR looks good to me, I have requested some changes to ensure this PR only does what is described in the summary. We'd have to push a coding style config to ensure all IDE's follow the same formatting rules.

2023-03-07 08:22 UTC, nbarnabee commented
> Hi @nbarnabee, there are no teritories on this project 😊. You're welcome to add improvements anytime.
> 
> This PR looks good to me, I have requested some changes to ensure this PR only does what is described in the summary. We'd have to push a coding style config to ensure all IDE's follow the same formatting rules.

Yeah, sorry, all of that was, of course, my IDE insisting on changes.

2023-03-07 08:47 UTC, blancadesal approved these changes

2023-03-07 08:48 UTC, merged